# Generated by Django 5.1.4 on 2024-12-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_id_slug_idx',
        ),
    ]
